#!/usr/bin/env python3
"""
Morning Briefing: Start-of-day summary

Aggregates:
- Weather (if configured)
- Calendar events (if configured)
- Task priorities from heartbeat-backlog.md
- Recent work from work-log.md
- Active decisions from WORKING_STATE.md

Usage:
    python3 tools/morning_briefing.py
    python3 tools/morning_briefing.py --deliver telegram  # Send to channel
"""

import argparse
import json
from datetime import datetime, timedelta
from pathlib import Path
from usage_logger import log_action
from usage_logger import log_usage

WORKSPACE = Path("/data/.openclaw/workspace")
WORKING_STATE = WORKSPACE / "WORKING_STATE.md"
WORK_LOG = WORKSPACE / "memory" / "work-log.md"
BACKLOG = WORKSPACE / "memory" / "heartbeat-backlog.md"
HEARTBEAT_STATE = WORKSPACE / "memory" / "heartbeat-state.json"

def get_current_focus():
    """Extract current focus from WORKING_STATE.md"""
    if not WORKING_STATE.exists():
        return "No active focus defined"
    
    content = WORKING_STATE.read_text()
    
    # Look for "Current Focus" section
    for line in content.split("\n"):
        if "Current Focus" in line or "🎯" in line:
            # Get next non-empty line
            lines = content.split("\n")
            idx = lines.index(line)
            for i in range(idx + 1, min(idx + 10, len(lines))):
                if lines[i].strip() and not lines[i].startswith("#"):
                    return lines[i].strip()
    
    return "No active focus defined"

def get_recent_work(days=1):
    """Get recent work from work-log.md"""
    if not WORK_LOG.exists():
        return []
    
    cutoff = datetime.now() - timedelta(days=days)
    recent = []
    
    for line in WORK_LOG.read_text().split("\n"):
        if line.strip() and "|" in line:
            # Format: timestamp | description | evidence
            parts = [p.strip() for p in line.split("|")]
            if len(parts) >= 2:
                recent.append(parts[1])
    
    return recent[-5:]  # Last 5 items

def get_priority_tasks(count=5):
    """Get top priority tasks from backlog"""
    if not BACKLOG.exists():
        return []
    
    tasks = []
    in_active = False
    
    for line in BACKLOG.read_text().split("\n"):
        if "## Active Backlog" in line or "## Active" in line:
            in_active = True
            continue
        
        if in_active:
            if line.startswith("##"):  # New section
                break
            
            if line.strip().startswith("- [ ]"):
                # Extract task description
                task = line.split("]", 1)[1].strip()
                tasks.append(task)
                
                if len(tasks) >= count:
                    break
    
    return tasks

def get_heartbeat_stats():
    """Get heartbeat statistics"""
    if not HEARTBEAT_STATE.exists():
        return {
            "work_items": 0,
            "consecutive_no_work": 0,
            "last_heartbeat": "Never"
        }
    
    try:
        state = json.load(open(HEARTBEAT_STATE))
        return {
            "work_items": state.get("heartbeatWorkItems", 0),
            "consecutive_no_work": state.get("consecutiveNoWork", 0),
            "last_heartbeat": state.get("lastHeartbeat", "Unknown")
        }
    except:
        return {
            "work_items": 0,
            "consecutive_no_work": 0,
            "last_heartbeat": "Unknown"
        }

def generate_briefing():
    """Generate morning briefing text"""
    now = datetime.now()
    
    briefing = []
    briefing.append(f"☀️ Morning Briefing - {now.strftime('%A, %B %d, %Y')}")
    briefing.append("")
    
    # Current Focus
    focus = get_current_focus()
    briefing.append("## 🎯 Current Focus")
    briefing.append(focus)
    briefing.append("")
    
    # Recent Work
    recent = get_recent_work()
    if recent:
        briefing.append("## ✅ Recent Work (Last 24h)")
        for item in recent:
            briefing.append(f"  • {item}")
        briefing.append("")
    
    # Priority Tasks
    tasks = get_priority_tasks()
    if tasks:
        briefing.append("## 📋 Priority Tasks (Top 5)")
        for i, task in enumerate(tasks, 1):
            briefing.append(f"  {i}. {task}")
        briefing.append("")
    
    # Heartbeat Stats
    stats = get_heartbeat_stats()
    briefing.append("## 💓 Heartbeat Stats")
    briefing.append(f"  • Work items completed: {stats['work_items']}")
    briefing.append(f"  • Consecutive no-work: {stats['consecutive_no_work']}")
    briefing.append(f"  • Last heartbeat: {stats['last_heartbeat']}")
    briefing.append("")
    
    # Footer
    briefing.append("---")
    briefing.append("_Generated by morning_briefing.py_")
    
    return "\n".join(briefing)

@log_usage
def main():
    parser = argparse.ArgumentParser(description="Generate morning briefing")
    parser.add_argument("--deliver", choices=["telegram", "discord"], help="Deliver to channel")
    parser.add_argument("--save", action="store_true", help="Save to file")
    
    args = parser.parse_args()
    
    briefing = generate_briefing()
    
    # Always print to console
    print(briefing)
    
    # Save to file if requested
    if args.save:
        output_path = WORKSPACE / "memory" / f"briefing-{datetime.now().strftime('%Y-%m-%d')}.md"
        output_path.write_text(briefing)
        print(f"\n✅ Saved to {output_path}")
    
    # Deliver to channel if requested
    if args.deliver:
        # TODO: Implement channel delivery via message tool
        print(f"\n⚠️ Channel delivery not yet implemented")
    
    # Log usage
    log_action("morning_briefing", "generate", success=True, 
               details={"delivered": args.deliver, "saved": args.save})

if __name__ == "__main__":
    main()
